### PR TITLE
feat: :sparkles: adds namespaces, enhances support for new arch

### PR DESCRIPTION
**Pull request by dsoffiantini**
## Description
Changes to packages to support new architecture if enabled, as well as namespacing android packages, which is a requirement in gradle 8/ rn 0.73

## How Has This Been Tested?

Regression on sample app has been successful

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cacheung** [comment]
Daniel, can you see if can take care of this ticket in this PR as well?
https://github.com/adobe/aepsdk-react-native/issues/259

**Comment by dsoffiantini** [comment]
> Daniel, can you see if can take care of this ticket in this PR as well? #259

@cacheung updated 👍 This should be good to go

**Comment by binarybaba** [comment]
Does this also fix https://github.com/adobe/aepsdk-react-native/issues/306 ??

**Comment by cacheung** [comment]
> Does this also fix #306 ??

This PR includes the namespace fix.  We are internally reviewing and testing.

**Pull request closed without merging**
