### PR TITLE
Messaging

### PR DESCRIPTION
**Pull request by dsoffiantini**
## Description

Updates to messaging to include latest IAM changes

## How Has This Been Tested?

Unit tests have been added

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cacheung** [comment]
Getting console warning when calling Refreshinappmessages() and Setmessagingdelegate() in the Messaging view of the sample app. new NativeEventEmitter() was called with a non-null arguement without the required 'removeLIsterners' method.   
Will this affect users who use messaging and optimize?

**Review by cacheung — COMMENTED** [review]
Need to regenerated a Podfile.lock for sample app.  The current one giving error when run pod install
[!] CocoaPods could not find compatible versions for pod "AEPEdge":
  In snapshot (Podfile.lock):
    AEPEdge (= 1.5.0, >= 1.1.0, >= 1.2.0, >= 1.4.0, ~> 1.0)

  In Podfile:
    AEPMessaging (from `https://github.com/adobe/aepsdk-messaging-ios.git`, branch `staging`) was resolved to 1.1.0-beta2, which depends on
      AEPEdge (>= 1.1.0)

    RCTAEPEdge (from `../../../packages/edge`) was resolved to 1.0.0, which depends on
      AEPEdge (~> 1.0)


You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * changed the constraints of dependency `AEPEdge` inside your development pod `RCTAEPEdge`.
   You should run `pod update AEPEdge` to apply changes you've made.

**Comment by cacheung** [comment]
Need to change the Sample App package.json to 1.0.0-beta.3  for messaging.

**Comment by dsoffiantini** [comment]
This is just a react native warning that doesnt affect functionality, but I can add some code to remove the warning

**Review by cacheung — APPROVED** [review]

**Pull request merged**
