### PR TITLE
fix: defer to root project's Android sdk version gradle params

### PR DESCRIPTION
**Pull request by kevindice**
## Description

The Android `build.gradle` files for each package here have hard-coded values for the `compileSdkVersion`, `minSdkVersion`, and `targetSdkVersion`.  This causes build errors with React Native 0.70.6:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':adobe_react-native-aepuserprofile:processDebugAndroidTestManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.facebook.react:react-native:0.70.6] /Users/kdice/.gradle/caches/transforms-3/4b3c55c96a7b7307f23241c80fa0f0d7/transformed/jetified-react-native-0.70.6-debug/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.facebook.react" to force usage (may lead to runtime failures)
```

This PR modifies each package's `build.gradle` file to defer to the params set by the root project using a common pattern I see in many other projects:

```
def safeExtGet(prop, fallback) {
    rootProject.ext.has(prop) ? rootProject.ext.get(prop) : fallback
}
```

## Related Issue

#222 

## Motivation and Context

This prevents Gradle conflicts concering the Android SDK version by deferring to params set by the root project.

## How Has This Been Tested?

This fixes my build and should cause no change in other contexts where there is no higher root project.

## Screenshots (if appropriate):

n/a

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have signed the [Adobe Open Source CLA](http://opensource.adobe.com/cla.html).
- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.   (n/a)

### CODE REVIEW

**Comment by yangyansong-adbe** [comment]
@kevindice, do you mind sharing which projects use the same way to manage Android API levels?

**Comment by kevindice** [comment]
Here are a few
- HoneyBadger react native client: https://github.com/honeybadger-io/honeybadger-react-native/blob/main/android/build.gradle#L17-L19
- `react-native-app-auth`: https://github.com/FormidableLabs/react-native-app-auth/blob/main/android/build.gradle#L1-L3
- `react-native-config`: https://github.com/luggit/react-native-config/blob/master/android/build.gradle#L14-L16
- `react-native-gesture-handler`: https://github.com/software-mansion/react-native-gesture-handler/blob/main/android/build.gradle#L30-L32
- `react-native-localize`: https://github.com/zoontek/react-native-localize/blob/master/android/build.gradle#L1-L3
- `react-native-orientation-locker`: https://github.com/wonday/react-native-orientation-locker/blob/master/android/build.gradle#L3-L5
- `react-native-permissions`: https://github.com/zoontek/react-native-permissions/blob/master/android/build.gradle#L1-L3
- `react-native-safe-area-context`: https://github.com/th3rdwave/react-native-safe-area-context/blob/main/android/build.gradle#L15-L17
- `react-native-svg`: https://github.com/software-mansion/react-native-svg/blob/main/android/build.gradle#L36-L38
- `react-native-vector-icons`: https://github.com/oblador/react-native-vector-icons/blob/master/android/build.gradle#L2-L4
- `react-native-webview`: https://github.com/react-native-webview/react-native-webview/blob/master/android/build.gradle#L2-L4

**Review by yangyansong-adbe — DISMISSED** [review]
LGTM

**Review by dsoffiantini — APPROVED** [review]

**Review by yangyansong-adbe — APPROVED** [review]

**Comment by yangyansong-adbe** [comment]
@kevindice, thanks for your contribution.

**Pull request merged**
